# Generated by Django 4.1.6 on 2023-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('nepali_name', models.CharField(max_length=100, null=True)),
                ('english_author', models.CharField(max_length=100, null=True)),
                ('nepali_author', models.CharField(max_length=100, null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('Publisher', models.CharField(max_length=100, null=True)),
                ('no_of_pages', models.IntegerField(null=True)),
                ('year_published', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
