# Generated by Django 4.1.6 on 2023-02-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
