# Generated by Django 4.1.6 on 2023-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_homebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
    ]
