# Generated by Django 4.1.6 on 2023-03-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
