# Generated by Django 4.1.6 on 2024-02-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_cart_alter_user_collection_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user33852', max_length=30),
        ),
    ]
